### ISSUE TITLE
Make it work with Babel 6

### ISSUE THREAD

**Issue by kmetsalu** [glortho/react-keydown#16] opened 2016-01-28 15:22 UTC
Currently it is working with Babel 5 decorators support, but something happens in [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy). 

I get an error:
![image](https://cloud.githubusercontent.com/assets/3165311/12648621/877ed188-c5e3-11e5-886d-af1a0383f2c0.png)

Using https://github.com/christianalfoni/webpack-express-boilerplate as a basis with babel-plugin-transform-decorators-legacy.

**Comment by glortho** [comment] 2016-01-28 15:38
@kmetsalu Are you decorating a class or method? Show me your code that has the `@keydown` call and I'll take a look.

**Comment by kmetsalu** [comment] 2016-01-28 17:20
@glortho  - Currently method.

``` javascript
import React from 'react';
import styles from './App.css';
import keydown from 'react-keydown';
export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {test: 'foo'};
  }

  @keydown('enter')
  changeState(e){
    console.log(e);
  }

  render() {
    return (
      <div className={styles.app}>
        bar
      </div>
    );
  }
}
```

from the boilerplate.

**Comment by glortho** [comment] 2016-01-28 19:11
@kmetsalu It turns out this is an issue with hot reloading + Babel 6: https://github.com/gaearon/react-transform-hmr/issues/36#issuecomment-173272351 (the example there is with classes but the same should be roughly true with method decorators that rely on the identity of a component class's prototype and the prototype of an instance of that class). @gaearon suggests it'll be fixed in Babel 7, but in the meantime it should work if you use Babel's react preset - https://babeljs.io/docs/plugins/preset-react/ - rather than the custom react-transform.

Closing this for now, but feel free to reopen if additional discussion is warranted.

**Closed as completed by glortho** 2016-01-28 19:11 UTC

**Comment by JonathanWi** [comment] 2016-02-05 22:14
Hey @glortho I'm having the same issue, even using the react-preset (which btw doesn't seem to compile decorator...). Any idea for a workaround? 

Thanks a lot :)

**Comment by glortho** [comment] 2016-02-05 22:23
Are you using the legacy decorator plugin for Babel 6?

**Comment by JonathanWi** [comment] 2016-02-05 22:28
Yes I am, if I remove decorators doesn't compile anymore... Thanks a lot for your quick reply

**Comment by JonathanWi** [comment] 2016-02-06 00:08
No method seems to work... Have you ever successfully make it work using ES6?

**Comment by glortho** [comment] 2016-02-06 00:25
Hm yes it works fine for us. Are you using HMR with webpack? Post your webpack and Babel configs and I'll take a look.

**Comment by JonathanWi** [comment] 2016-02-06 00:31
Thank you!

I've created a gist with my webpack / babel config available here : https://gist.github.com/JonathanWi/b9798b37263240592b9a

**Comment by glortho** [comment] 2016-02-06 01:10
It looks maybe like you're using HMR? If so it's possible that's the problem. If you're not using it I'll see if I can replicate with a similar set-up. If you can try with HMR enabled vs disabled and tell me the results it'll help with troubleshooting.

**Comment by JonathanWi** [comment] 2016-02-06 10:14
I'm using [HMRE](https://github.com/danmartinez101/babel-preset-react-hmre), which is HMR with error catching. What should I use if it's currently not compatible with HMR?

**Comment by JonathanWi** [comment] 2016-02-06 12:32
@glortho I disabled HMRE and now it works fine (even tho I don't have the hot module reload, which is a pain). Do you know of a workaround? Thanks for your help

**Comment by gaearon** [comment] 2016-02-06 13:37
Please file an issue with babel-plugin-react-transform and we can take a look. Please make sure to publish a project reproducing the issue so it’s easier to reproduce the problem.

**Comment by glortho** [comment] 2016-02-06 18:17
@gaearon @JonathanWi I don't know if this is a bug as much as an implementation incompatibility. react-keydown stores bindings in a map keyed by the prototype of the bound component class. When an instance of that class is mounted, and a keydown event is triggered, we match the prototype of that instance to the protoype key in the bindings map. (See the block that follows here: https://github.com/glortho/react-keydown/blob/master/src/store.js#L75.)

I don't know much about HMR but my assumption is that the component class has been swapped out for a proxy class, and thus the instance prototypes don't match the proxy class prototype. Does this sound right @gaearon?

Comments from this link above resonate with me as to why HMR would work with Babel 5 but not Babel 6: https://github.com/gaearon/react-transform-hmr/issues/36#issuecomment-173272351

**Comment by gaearon** [comment] 2016-02-06 19:19
The new Babel 6.5.0 passPerPreset option might help here.

**Comment by glortho** [comment] 2016-02-06 19:29
Thanks @gaearon.

@kmetsalu @JonathanWi @dbachko you could try the referenced Babel 6.5.0 feature, ensuring that the legacy decorator plugin is traversed before anything else: https://github.com/babel/babel/blob/master/CHANGELOG.md#a-traversal-per-preset. But I'm not sure how that will interact with HMR settings set elsewhere.

You can also try this workaround to see if it helps: https://github.com/gaearon/react-transform-hmr/issues/36#issuecomment-173273055

I'll do my own investigation in the meantime.

**Comment by JonathanWi** [comment] 2016-02-07 11:47
@gaearon @glortho Thanks for the help. When updating to Babel 6.5.0, it appears that `babel-plugin-transform-decorators-legacy` breaks (Decorators are not supported yet on compile, which wasn't the case in 6.4.5). 

Using the work around described [here](https://github.com/gaearon/react-transform-hmr/issues/36#issuecomment-173273055) doesn't work either and breaks on compile.

I must say that this behavior is only related to this plugin, since I successfuly use decorator with HMR with [react-anything-sortable](https://github.com/jasonslyvia/react-anything-sortable).

Thanks a lot for your time on this issue

**Comment by glortho** [comment] 2016-02-07 13:19
Okay thank you for helping us track down the issue here @jonathanwi. We'll see what happens when everything compiles predictably on 6.5 but otherwise it seems we may need to work on a version that is more compatible with HMR. Stay tuned and please do let us know if you discover anything else.

**Comment by gaearon** [comment] 2016-02-07 13:30
> I don't know much about HMR but my assumption is that the component class has been swapped out for a proxy class, and thus the instance prototypes don't match the proxy class prototype. Does this sound right @gaearon?

I’m not sure. We should set up all the properties correctly. See tests in https://github.com/gaearon/react-proxy/blob/master/test/consistency.js. 

If you can provide a failing test that would help.

**Comment by glortho** [comment] 2016-02-07 19:10
@JonathanWi @kmetsalu @dbachko See if 1.4.8 works for you (just pushed), which uses uuids instead of prototype refs as keys for bindings.

Thanks for your attention to this issue @gaearon - your tests confirmed that a failing test there would defy your intended functionality. In other words, since we were using prototype refs themselves as keys in our bindings Map (we might have been overlay enamored with non-scalar keys), proxy prototypes would have needed not just to mirror properties from the original class prototypes but actually BE the original class prototypes. The switch to uuid strings in 1.4.8 should hopefully resolve the issue.

**Comment by JonathanWi** [comment] 2016-02-07 19:14
This is awesome @glortho, it works perfectly for me!

**Comment by glortho** [comment] 2016-02-07 19:15
Good news @JonathanWi!
