### ISSUE TITLE
Not working on IE11 ?!

### ISSUE THREAD

**Issue by X-Tender** [glortho/react-keydown#33] opened 2016-10-06 08:42 UTC
Add a @keydown( 'right' );
Decorator to my function, it works on Chrome and Safari perfectly but on IE it doesnt do anything.
Is there a ways to debut it, for exaple get infrimations if the key event was triggered in the component when the key was pressed?

**Comment by glortho** [comment] 2016-10-06 17:18
I think this is probably a duplicate of https://github.com/glortho/react-keydown/issues/29. I should be able to get to this within a few days.

**Comment by glortho** [comment] 2016-10-29 19:17
Sorry for the delay @X-Tender . Try it out now (v1.6.3) and see if it works.

**Closed as completed by glortho** 2016-10-29 19:17 UTC
