### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by dbachko** [glortho/react-keydown#18] opened 2016-02-04 22:24 UTC
I am getting this error when I am trying to decorate method

![screen shot 2016-02-04 at 5 11 44 pm](https://cloud.githubusercontent.com/assets/9260214/12831775/21104e5a-cb64-11e5-8e81-8e60c3dbd4ee.png)

**Comment by glortho** [comment] 2016-02-04 22:25
Hi @dbachko . This is very likely a duplicate of https://github.com/glortho/react-keydown/issues/16. Feel free to reopen if more discussion is warranted.

**Closed as completed by glortho** 2016-02-04 22:25 UTC

**Comment by dbachko** [comment] 2016-02-04 22:29
Thank you

**Comment by k7sleeper** [comment] 2016-11-24 10:48
I've included `<script src="vendor/core.js"></script>` at the top of my web pages to solve this problem in IE11.
